version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./psql_data:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:5432"
    expose:
      - 5432

  fastapiservice:
    build: .
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "8000:8000"
    expose:
      - "8000"